### ISSUE TITLE
Isomorphic

### ISSUE THREAD

**Issue by jul-** [weblancaster/node-react-stack-kit#5]
This stack is not isomorphic, is it?

**Comment by quoo** [comment]
+1

**Comment by weblancaster** [comment]
@jul- and @quoo correct, this is not isomorphic.

Although that can be changed, instead of using hbs to render the view from the server you can change to be React that way making isomorphic.

Isomorphic is a complex world where the architecture need to be very well implemented that way the same code that runs in the client also runs in the server (MVC doesn't work that way).
