### ISSUE TITLE
Test coverage not working ?

### ISSUE THREAD

**Issue by ButuzGOL** [weblancaster/node-react-stack-kit#9]

**Comment by weblancaster** [comment]
Hey @ButuzGOL can you give me more information please, on what's going on besides the title?

How are you running the test? do you have a log? what your console/terminal says? did you see the coverage folder after running the test?

**Comment by ButuzGOL** [comment]
I thought that test coverage not working and create this issue
so after you question I decided to do recheck and clone repo
so now I have this issue

```
 ➜  node-react-stack-kit git:(master) npm test

> node-react-stack-kit@1.0.0 test /Users/butuzgol/Playground/node-react-stack-kit
> karma start karma.conf.js

10 01 2016 22:38:47.762:ERROR [karma]: { [Error: no such file or directory]
  code: 'ENOENT',
  errno: 34,
  message: 'no such file or directory',
  path: '/_karma_webpack_/test/sample-spec.js' }
Error: no such file or directory
```

**Comment by weblancaster** [comment]
@ButuzGOL After do some updates while ago I forgot to update the path in the test.. this is fixed now and you can update with your local repo.. thanks for letting us know.

**Comment by ButuzGOL** [comment]
Currently coverage shows me 

```
Statements   : 100% ( 0/0 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 0/0 )
```

And its not right
I can try to do pull request ?

**Comment by weblancaster** [comment]
@ButuzGOL what you are seeing is what should be happening.. therefore the tests are fine, let me explain though.

We have no `statements`, `branches`, `functions` or `lines` being tested what we are testing is jsx ("markup") code (can you imagine if the markup had to have line coverage/tests.. that's not what you really want to test).

Take a look what we are testing https://github.com/isobar-idev/node-react-stack-kit/blob/master/public/javascripts/components/header.jsx#L13

and here's the unit test https://github.com/isobar-idev/node-react-stack-kit/blob/master/test/sample-spec.js#L18 as you can see there's no logic being tested that's why we have.

```
Statements   : 100% ( 0/0 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 0/0 )
```

**Comment by ButuzGOL** [comment]
You can update your test and you will that test coverage not working properly
for example

```
render () {
    const className = 'header';
    return (
      <nav className={className}>
     ....
   )
}
```
